version: '3.8'
services:
  api-roach:
    depends_on:
      - roach
    build:
      context: .
      target: ${STAGE}
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - PGUSER=${PGUSER:-dev}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  roach:
    image: cockroachdb/cockroach:latest-v24.3
    container_name: roach
    hostname: db
    networks:
      - mynet
    ports:
      - ${PGPORT:-26257}:${PGPORT:-26257}
      - ${CRPORT:-8080}:${CRPORT:-8080}
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach:

networks:
  mynet:
    driver: bridge